version: '3'
 
services:
  frontend:
    image: emil064/recruit-front:latest
    container_name: recruit-front
    ports:
      - '8181:8888'
    restart: always
    networks:
      - recruit-net
  backend:
    image: emil064/recruit-back:latest
    container_name: recruit-back
    ports:
      - '3000:3000'
    restart: always
    networks:
      - recruit-net
    depends_on:
      - db
  db:
    image: emil064/recruit-db:latest
    container_name: recruit-db
    ports:
      - '3306:3306'
    restart: always
    networks:
      - recruit-net
networks:
  recruit-net:
    name: recruit-net